// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
async function injectDeps(deps) {
	return await new Promise((resolve, reject) => {
		if (!Array.isArray(deps)) {
			deps = [deps];
		}
		window.dojoDynamicRequire(deps, function () { resolve(Array.from(arguments)) });
	});
}
// END EXTRA CODE

/**
 * @param {string} targetId
 * @param {string} config
 * @returns {Promise.<void>}
 */
export async function Lock(targetId, config) {
	// BEGIN USER CODE
	const [on, lang] = await injectDeps(["dojo/on", "dojo/_base/lang"]);
	const container = document.querySelector('#' + targetId);

	on(container, 'load', (e) => {
		const data = e.data;
		on.emit(container, 'lock', {
			data: {
				"authority": {//Permission configuration of the current worksheet
					selectLockedCells: 1, //Select locked cells
					selectunLockedCells: 1, //Select unlocked cells
					formatCells: 1, //Format cells
					formatColumns: 1, //Format columns
					formatRows: 1, //Format rows
					insertColumns: 1, //Insert columns
					insertRows: 1, //Insert rows
					insertHyperlinks: 1, //Insert hyperlinks
					deleteColumns: 1, //Delete columns
					deleteRows: 1, //Delete rows
					sort: 1, //Sort
					filter: 1, //Filter
					usePivotTablereports: 1, //Use Pivot Table reports
					editObjects: 1, //Edit objects
					editScenarios: 1, //Edit scenarios   
					sheet: 1, //If it is 1 or true, the worksheet is protected; if it is 0 or false, the worksheet is not protected.
					hintText: "", //The text of the pop-up prompt
					algorithmName: "None",//Encryption scheme: MD2,MD4,MD5,RIPEMD-128,RIPEMD-160,SHA-1,SHA-256,SHA-384,SHA-512,WHIRLPOOL
					saltValue: null, //The salt parameter for password decryption is a random value set by yourself

					allowRangeList: [
						{ //Range protection
							name: "area", //Name
							//password: "1", //Password
							//hintText: "", //Prompt text
							//algorithmName: "None",//Encryption scheme: MD2,MD4,MD5,RIPEMD-128,RIPEMD-160,SHA-1,SHA-256,SHA-384,SHA-512,WHIRLPOOL
							//saltValue: null, //The salt parameter for password decryption is a random value set by yourself
							sqref: "$A$2:$C$5" //Protected range
						}
					],
				}, //Worksheet protection
			}
		});
	});
	// END USER CODE
}
