// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE

async function injectDeps(deps) {
	return await new Promise((resolve, reject) => {
		if (!Array.isArray(deps)) {
			deps = [deps];
		}
		window.dojoDynamicRequire(deps, function() { resolve(Array.from(arguments)) });
	});
}
// END EXTRA CODE

/**
 * @param {string} containerId
 * @param {string} sheetTitle
 * @param {MxObject} ctx
 * @param {boolean} collaborate
 * @returns {Promise.<void>}
 */
export async function RenderFormFill(containerId, sheetTitle, ctx, collaborate) {
	// BEGIN USER CODE
	const [on] = await injectDeps(["dojo/on"]);
	const iframeId = `ls_${containerId}`;
	const container = document.querySelector('#' + containerId);

	
	function sendCommand(msg) {
		msg.mx_luckysheet.widgetid = containerId;
		container.querySelector(`#${iframeId}`).contentWindow && container.querySelector(`#${iframeId}`).contentWindow.postMessage(msg, '*');
	
	}
	const [html] = await injectDeps('dojo/html');
	let entityData = {
		"name": sheetTitle, //Worksheet name
		"color": "", //Worksheet color
		"index": 1, //Worksheet index
		"status": 0, //Worksheet active status
		"order": 1, //The order of the worksheet
		"hide": 0,//Whether worksheet hide 
		"row": 36, //the number of rows in a sheet
		"column": 18, //the number of columns in a sheet
		"defaultRowHeight": 19, //Customized default row height
		"defaultColWidth": 73, //Customized default column width
		"celldata": [], //Initial the cell data
		"config": {
			"merge": {}, //merged cells
			"rowlen": {}, //Table row height
			"columnlen": {}, //Table column width
			"rowhidden": {}, //hidden rows
			"colhidden": {}, //hidden columns
			"borderInfo": {}, //borders
			"authority": {//Permission configuration of the current worksheet
				selectLockedCells: 1, //Select locked cells
				selectunLockedCells: 1, //Select unlocked cells
				formatCells: 1, //Format cells
				formatColumns: 1, //Format columns
				formatRows: 1, //Format rows
				insertColumns: 1, //Insert columns
				insertRows: 1, //Insert rows
				insertHyperlinks: 1, //Insert hyperlinks
				deleteColumns: 1, //Delete columns
				deleteRows: 1, //Delete rows
				sort: 1, //Sort
				filter: 1, //Filter
				usePivotTablereports: 1, //Use Pivot Table reports
				editObjects: 1, //Edit objects
				editScenarios: 1, //Edit scenarios   
				sheet: 1, //If it is 1 or true, the worksheet is protected; if it is 0 or false, the worksheet is not protected.
				hintText: "", //The text of the pop-up prompt
				algorithmName: "None",//Encryption scheme: MD2,MD4,MD5,RIPEMD-128,RIPEMD-160,SHA-1,SHA-256,SHA-384,SHA-512,WHIRLPOOL
				saltValue: null, //The salt parameter for password decryption is a random value set by yourself
    
				allowRangeList: [
					{ //Range protection
						name: "area", //Name
						password: "1", //Password
						hintText: "", //Prompt text
						algorithmName: "None",//Encryption scheme: MD2,MD4,MD5,RIPEMD-128,RIPEMD-160,SHA-1,SHA-256,SHA-384,SHA-512,WHIRLPOOL
						saltValue: null, //The salt parameter for password decryption is a random value set by yourself
						sqref: "$C$1:$D$5" //Protected range
					},
					{ //Range protection
						name: "area", //Name
						//password: "1", //Password
						//hintText: "", //Prompt text
						//algorithmName: "None",//Encryption scheme: MD2,MD4,MD5,RIPEMD-128,RIPEMD-160,SHA-1,SHA-256,SHA-384,SHA-512,WHIRLPOOL
						//saltValue: null, //The salt parameter for password decryption is a random value set by yourself
						sqref: "$F$1:$F$1" //Protected range
					}
				],
			}, //Worksheet protection
		},
		"scrollLeft": 0, //Left and right scroll bar position
		"scrollTop": 0, //Up and down scroll bar position
		"luckysheet_select_save": [], //selected area
		"calcChain": [],//Formula chain
		"isPivotTable": false,//Whether is pivot table
		"pivotTable": {},//Pivot table settings
		"filter_select": {},//Filter range
		"filter": null,//Filter configuration
		"luckysheet_alternateformat_save": [], //Alternate colors
		"luckysheet_alternateformat_save_modelCustom": [], //Customize alternate colors	
		"luckysheet_conditionformat_save": {},//condition format
		"frozen": {}, //freeze row and column configuration
		"chart": [], //Chart configuration
		"zoomRatio": 1, // zoom ratio
		"image": [], //image
		"showGridLines": 1, //Whether to show grid lines
	};

	on(container, 'lock', (e) => {
		const data = e.data;
		entityData.config.authority.allowRangeList = [];
		sendCommand({
			mx_luckysheet: {
				id: 'lock', 
				data
			}
		});
	});

	//响应LuckySheet事件
	window.addEventListener("message", (event) => {
		if (event.data.mx_luckysheet && event.data.mx_luckysheet.widgetid === containerId) {
			const data = event.data.mx_luckysheet.data;
			switch (event.data.mx_luckysheet.id) {
				case 'load':
					//事件 成功载入
					sendCommand({
						mx_luckysheet: {
							id: 'setup', 
							data: [entityData],
							updateUrl: collaborate ? `${mx.appUrl}ws`.replaceAll('http://', 'ws://').replaceAll('https://', 'wss://') : '', lang: mx.session.sessionData.locale.code.split('_')[0]
						}
					});
					on.emit(container, 'load', { bubbles: true, data: {} });
					break;
				case 'cell_updated':
					/*const data = event.data.mx_luckysheet.data;
								const idx = isVertical ? (data.r - start) / offset : (data.c - start) / offset;
								const obj = cache.get(containerId)[idx];
								if (isVertical) {
									obj.set(columns.get(data.c + 1)[1], data.newValue.v);
								} else {
									obj.set(columns.get(data.r + 1)[1], data.newValue.v);
								}
								mx.data.commit({
									mxobj: obj,
									callback: function() {
										console.log("Object committed");
										mx.data.update({
											entity: entity,
										});
									},
									error: function(e) {
										console.error("Could not commit object:", e);
									}
								});*/
								
					on.emit(container, 'cell_updated', { bubbles: true, data });
					break;
				case 'rangeSelect':
					on.emit(container, 'rangeSelect', { bubbles: true, data });
					break;
			}
			
		}
	}, false);
	
	if (container.innerHTML == '') {

		//首次渲染
		html.set(container, `
		<iframe id="${iframeId}" src="resources/luckysheet.html?widgetid=${containerId}" style="
    width: 100%;
    height: 100%;
    border: 0;
"></iframe>
		`);


	} else {
		
	}
	// END USER CODE
}
