// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
async function fetchPage(entity, nameAtts) {
	return await new Promise((resolve, reject) => {
		mx.data.get({
			//Entity_2
			xpath: '//' + entity,
			count: true, filter: {
				attributes: nameAtts,
				//sort: [['createdDate', 'asc']],
				//offset,
				//amount, 
				//references: { 'MyFirstModule.Part_ProduceLog': { attributes: ['Week', 'Sum'], sort: [['Week', 'asc']] } }
			}, callback: (objs, extra) => {
				resolve([objs, extra]);
			}
		});
	});

}

const demo = {
	name: "Cell",
	index: 0,
	zoomRatio: 1,
	order: 0,
	status: 0,
	celldata: [
		{
			r: 0,
			c: 0,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1,
				v: 1,
				ct: { fa: "General", t: "n" },
				m: "1"
			}
		},
		{
			r: 0,
			c: 1,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1,
				v: 2,
				ct: { fa: "General", t: "n" },
				m: "2"
			}
		},
		{
			r: 0,
			c: 2,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1,
				v: 3,
				ct: { fa: "General", t: "n" },
				m: "3"
			}
		},
		{
			r: 0,
			c: 3,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1,
				v: 0,
				ct: { fa: "General", t: "n" },
				m: "0",
				f: "=Formula!D3+Formula!D4"
			}
		},
		{
			r: 0,
			c: 4,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 0,
			c: 5,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 0,
			c: 6,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 0,
			c: 7,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 0,
			c: 8,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 0,
			c: 9,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 0,
			c: 10,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 1,
			c: 0,
			v: {
				v: "Background",
				ct: { fa: "General", t: "g" },
				m: "Background",
				bg: null,
				bl: 1,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 1,
			c: 1,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 1,
			c: 2,
			v: {
				bg: "rgb(30, 144, 255)",
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 1,
			c: 3,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 1,
			c: 4,
			v: {
				bg: "rgb(0, 255, 0)",
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 1,
			c: 5,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 1,
			c: 6,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 1,
			c: 7,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 1,
			c: 8,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 1,
			c: 9,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 1,
			c: 10,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 2,
			c: 0,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 2,
			c: 1,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 2,
			c: 2,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 2,
			c: 3,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 2,
			c: 4,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 2,
			c: 5,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 2,
			c: 6,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 2,
			c: 7,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 2,
			c: 8,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 2,
			c: 9,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 2,
			c: 10,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 3,
			c: 0,
			v: {
				v: "Border",
				ct: { fa: "General", t: "g" },
				m: "Border",
				bg: null,
				bl: 1,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 3,
			c: 1,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 3,
			c: 2,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 3,
			c: 3,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 3,
			c: 4,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 3,
			c: 5,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 3,
			c: 6,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 3,
			c: 7,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 3,
			c: 8,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 3,
			c: 9,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 3,
			c: 10,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 4,
			c: 0,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 4,
			c: 1,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 4,
			c: 2,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 4,
			c: 3,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 4,
			c: 4,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 4,
			c: 5,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 4,
			c: 6,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 4,
			c: 7,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 4,
			c: 8,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 4,
			c: 9,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 4,
			c: 10,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 5,
			c: 0,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1,
				ct: {
					fa: "General",
					t: "inlineStr",
					s: [
						{
							ff: "Arial",
							fc: "rgb(255, 0, 0)",
							fs: 12,
							cl: 0,
							un: 0,
							bl: 0,
							it: 0,
							v: "Inline"
						},
						{
							ff: "Arial",
							fc: "#000000",
							fs: 12,
							cl: 0,
							un: 0,
							bl: 0,
							it: 0,
							v: " "
						},
						{
							ff: "Arial",
							fc: "#000000",
							fs: 16,
							cl: 1,
							un: 0,
							bl: 0,
							it: 1,
							v: "Style"
						},
						{
							ff: "Arial",
							fc: "#000000",
							fs: 12,
							cl: 0,
							un: 0,
							bl: 0,
							it: 0,
							v: " "
						},
						{
							ff: "Arial",
							fc: "#000000",
							fs: 12,
							cl: 0,
							un: 0,
							bl: 1,
							it: 0,
							v: "Cell"
						}
					]
				}
			}
		},
		{
			r: 5,
			c: 1,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 5,
			c: 2,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 5,
			c: 3,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 5,
			c: 4,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 5,
			c: 5,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 5,
			c: 6,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 5,
			c: 7,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 5,
			c: 8,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 5,
			c: 9,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 5,
			c: 10,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 6,
			c: 0,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 6,
			c: 1,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 6,
			c: 2,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 6,
			c: 3,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 6,
			c: 4,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 6,
			c: 5,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 6,
			c: 6,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 6,
			c: 7,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 6,
			c: 8,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 6,
			c: 9,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 6,
			c: 10,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 7,
			c: 0,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 7,
			c: 1,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 7,
			c: 2,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 7,
			c: 3,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 7,
			c: 4,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 7,
			c: 5,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 7,
			c: 6,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 7,
			c: 7,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 7,
			c: 8,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 7,
			c: 9,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 7,
			c: 10,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 8,
			c: 0,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 8,
			c: 1,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 8,
			c: 2,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 8,
			c: 3,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 8,
			c: 4,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 8,
			c: 5,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 8,
			c: 6,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 8,
			c: 7,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 8,
			c: 8,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 8,
			c: 9,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 8,
			c: 10,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 9,
			c: 0,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 9,
			c: 1,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 9,
			c: 2,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 9,
			c: 3,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 9,
			c: 4,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 9,
			c: 5,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 9,
			c: 6,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 9,
			c: 7,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 9,
			c: 8,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 9,
			c: 9,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 9,
			c: 10,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 10,
			c: 0,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 10,
			c: 1,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 10,
			c: 2,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 10,
			c: 3,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 10,
			c: 4,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 10,
			c: 5,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 10,
			c: 6,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 10,
			c: 7,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 10,
			c: 8,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 10,
			c: 9,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 10,
			c: 10,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 11,
			c: 0,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 11,
			c: 1,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 11,
			c: 2,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 11,
			c: 3,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 11,
			c: 4,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 11,
			c: 5,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 11,
			c: 6,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 11,
			c: 7,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 11,
			c: 8,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 11,
			c: 9,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 11,
			c: 10,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 12,
			c: 0,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 12,
			c: 1,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 12,
			c: 2,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 12,
			c: 3,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 12,
			c: 4,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 12,
			c: 5,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 12,
			c: 6,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 12,
			c: 7,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 12,
			c: 8,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 12,
			c: 9,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 12,
			c: 10,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 13,
			c: 0,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 13,
			c: 1,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 13,
			c: 2,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 13,
			c: 3,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 13,
			c: 4,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 13,
			c: 5,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1,
				mc: { r: 13, c: 5, rs: 3, cs: 1 }
			}
		},
		{
			r: 13,
			c: 6,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 13,
			c: 7,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1,
				mc: { r: 13, c: 7, rs: 3, cs: 2 }
			}
		},
		{ r: 13, c: 8, v: { mc: { r: 13, c: 7 } } },
		{
			r: 13,
			c: 9,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 13,
			c: 10,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 14,
			c: 0,
			v: {
				v: "Span",
				ct: { fa: "General", t: "g" },
				m: "Span",
				bg: null,
				bl: 1,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 14,
			c: 1,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 14,
			c: 2,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1,
				mc: { r: 14, c: 2, rs: 1, cs: 2 }
			}
		},
		{ r: 14, c: 3, v: { mc: { r: 14, c: 2 } } },
		{
			r: 14,
			c: 4,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{ r: 14, c: 5, v: { mc: { r: 13, c: 5 } } },
		{
			r: 14,
			c: 6,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{ r: 14, c: 7, v: { mc: { r: 13, c: 7 } } },
		{ r: 14, c: 8, v: { mc: { r: 13, c: 7 } } },
		{
			r: 14,
			c: 9,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 14,
			c: 10,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 15,
			c: 0,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 15,
			c: 1,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 15,
			c: 2,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 15,
			c: 3,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 15,
			c: 4,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{ r: 15, c: 5, v: { mc: { r: 13, c: 5 } } },
		{
			r: 15,
			c: 6,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{ r: 15, c: 7, v: { mc: { r: 13, c: 7 } } },
		{ r: 15, c: 8, v: { mc: { r: 13, c: 7 } } },
		{
			r: 15,
			c: 9,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 15,
			c: 10,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1,
				mc: { r: 15, c: 10, rs: 4, cs: 3 }
			}
		},
		{ r: 15, c: 11, v: { mc: { r: 15, c: 10 } } },
		{ r: 15, c: 12, v: { mc: { r: 15, c: 10 } } },
		{
			r: 16,
			c: 0,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 16,
			c: 1,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 16,
			c: 2,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 16,
			c: 3,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 16,
			c: 4,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 16,
			c: 5,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 16,
			c: 6,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 16,
			c: 7,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 16,
			c: 8,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 16,
			c: 9,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 16,
			c: 10,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1,
				mc: { r: 15, c: 10 }
			}
		},
		{ r: 16, c: 11, v: { mc: { r: 15, c: 10 } } },
		{ r: 16, c: 12, v: { mc: { r: 15, c: 10 } } },
		{
			r: 17,
			c: 0,
			v: {
				v: "Font",
				ct: { fa: "General", t: "g" },
				m: "Font",
				bg: null,
				bl: 1,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 17,
			c: 1,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 17,
			c: 2,
			v: {
				v: "Luckysheet",
				ct: { fa: "General", t: "g" },
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: "11",
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1,
				m: "Luckysheet"
			}
		},
		{
			r: 17,
			c: 3,
			v: {
				v: "Luckysheet",
				ct: { fa: "General", t: "g" },
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 13,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1,
				m: "Luckysheet"
			}
		},
		{
			r: 17,
			c: 4,
			v: {
				v: "Luckysheet",
				ct: { fa: "General", t: "g" },
				bg: null,
				bl: 0,
				it: 0,
				ff: 9,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1,
				m: "Luckysheet"
			}
		},
		{
			r: 17,
			c: 5,
			v: {
				v: "Luckysheet",
				ct: { fa: "General", t: "g" },
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 13,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1,
				m: "Luckysheet"
			}
		},
		{
			r: 17,
			c: 6,
			v: {
				v: "Luckysheet",
				ct: { fa: "General", t: "g" },
				bg: "rgb(255, 215, 0)",
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1,
				m: "Luckysheet"
			}
		},
		{
			r: 17,
			c: 7,
			v: {
				v: "Luckysheet",
				ct: { fa: "General", t: "g" },
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(67, 110, 238)",
				ht: 1,
				vt: 1,
				m: "Luckysheet"
			}
		},
		{
			r: 17,
			c: 8,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 17,
			c: 9,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 17,
			c: 10,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1,
				mc: { r: 15, c: 10 }
			}
		},
		{ r: 17, c: 11, v: { mc: { r: 15, c: 10 } } },
		{ r: 17, c: 12, v: { mc: { r: 15, c: 10 } } },
		{
			r: 18,
			c: 0,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 18,
			c: 1,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 18,
			c: 2,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 18,
			c: 3,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 18,
			c: 4,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 18,
			c: 5,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 18,
			c: 6,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 18,
			c: 7,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 18,
			c: 8,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 18,
			c: 9,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 18,
			c: 10,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1,
				mc: { r: 15, c: 10 }
			}
		},
		{ r: 18, c: 11, v: { mc: { r: 15, c: 10 } } },
		{ r: 18, c: 12, v: { mc: { r: 15, c: 10 } } },
		{
			r: 19,
			c: 0,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 19,
			c: 1,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 19,
			c: 2,
			v: {
				v: "Luckysheet",
				ct: { fa: "General", t: "g" },
				bg: "rgb(67, 110, 238)",
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(255, 215, 0)",
				ht: 1,
				vt: 1,
				m: "Luckysheet"
			}
		},
		{
			r: 19,
			c: 3,
			v: {
				v: "Luckysheet",
				ct: { fa: "General", t: "g" },
				bg: null,
				bl: 1,
				it: 0,
				ff: 0,
				fs: "10",
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1,
				m: "Luckysheet"
			}
		},
		{
			r: 19,
			c: 4,
			v: {
				v: "Luckysheet",
				ct: { fa: "General", t: "g" },
				bg: null,
				bl: 0,
				it: 1,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1,
				m: "Luckysheet"
			}
		},
		{
			r: 19,
			c: 5,
			v: {
				v: "Luckysheet",
				ct: { fa: "General", t: "g" },
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1,
				cl: 1,
				m: "Luckysheet"
			}
		},
		{
			r: 19,
			c: 6,
			v: {
				ct: { fa: "General", t: "g" },
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: "1",
				vt: "0",
				cl: 1
			}
		},
		{
			r: 19,
			c: 7,
			v: {
				ct: { fa: "General", t: "g" },
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 19,
			c: 8,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 19,
			c: 9,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 19,
			c: 10,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 20,
			c: 0,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 20,
			c: 1,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 20,
			c: 2,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 20,
			c: 3,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 20,
			c: 4,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 20,
			c: 5,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 20,
			c: 6,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 20,
			c: 7,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 20,
			c: 8,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 20,
			c: 9,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 20,
			c: 10,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 21,
			c: 0,
			v: {
				v: "Format",
				ct: { fa: "General", t: "g" },
				m: "Format",
				bg: null,
				bl: 1,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 21,
			c: 1,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 21,
			c: 2,
			v: {
				ct: { fa: "##0.00", t: "n" },
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1,
				m: "0.25",
				v: 0.25
			}
		},
		{
			r: 21,
			c: 3,
			v: {
				ct: { fa: "$#,##0.00_);($#,##0.00)", t: "n" },
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1,
				m: "$0.25 ",
				v: 0.25
			}
		},
		{
			r: 21,
			c: 4,
			v: {
				ct: { fa: '"$" 0.00', t: "n" },
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1,
				m: "$ 0.25",
				v: 0.25
			}
		},
		{
			r: 21,
			c: 5,
			v: {
				ct: { fa: "0%", t: "n" },
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1,
				m: "25%",
				v: 0.25
			}
		},
		{
			r: 21,
			c: 6,
			v: {
				ct: { fa: "# ?/?", t: "n" },
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1,
				m: " 1/4",
				v: 0.25
			}
		},
		{
			r: 21,
			c: 7,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 21,
			c: 8,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 21,
			c: 9,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 21,
			c: 10,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 22,
			c: 0,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 22,
			c: 1,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 22,
			c: 2,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 22,
			c: 3,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 22,
			c: 4,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 22,
			c: 5,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 22,
			c: 6,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 22,
			c: 7,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 22,
			c: 8,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 22,
			c: 9,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 22,
			c: 10,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 23,
			c: 0,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 23,
			c: 1,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 23,
			c: 2,
			v: {
				ct: { fa: "0.00E+00", t: "n" },
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1,
				m: "2.50E-01",
				v: 0.25
			}
		},
		{
			r: 23,
			c: 3,
			v: {
				v: 0.25,
				ct: { fa: "0.00", t: "n" },
				m: "0.25",
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 23,
			c: 4,
			v: {
				ct: { fa: "AM/PM h:mm:ss", t: "d" },
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1,
				v: 44032,
				m: "AM 12:00:00"
			}
		},
		{
			r: 23,
			c: 5,
			v: {
				ct: { fa: "yyyy/MM/dd", t: "d" },
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1,
				v: 44032,
				m: "2020/07/20"
			}
		},
		{
			r: 23,
			c: 6,
			v: {
				ct: { fa: 'yyyy"年"M"月"d"日"', t: "d" },
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1,
				v: 44032,
				m: "2020年7月20日"
			}
		},
		{
			r: 23,
			c: 7,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 23,
			c: 8,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 23,
			c: 9,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 23,
			c: 10,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 24,
			c: 0,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 24,
			c: 1,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 24,
			c: 2,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 24,
			c: 3,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 24,
			c: 4,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 24,
			c: 5,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 24,
			c: 6,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 24,
			c: 7,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 24,
			c: 8,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 24,
			c: 9,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 24,
			c: 10,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 25,
			c: 0,
			v: {
				v: "Alignment",
				ct: { fa: "General", t: "g" },
				m: "Alignment",
				bg: null,
				bl: 1,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 25,
			c: 1,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 25,
			c: 2,
			v: {
				v: "Top Left",
				ct: { fa: "General", t: "g" },
				m: "Top Left",
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: "1",
				vt: "1"
			}
		},
		{
			r: 25,
			c: 3,
			v: {
				v: "Top Center",
				ct: { fa: "General", t: "g" },
				m: "Top Center",
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: "0",
				vt: "1"
			}
		},
		{
			r: 25,
			c: 4,
			v: {
				v: "Top Right",
				ct: { fa: "General", t: "g" },
				m: "Top Right",
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: "2",
				vt: "1"
			}
		},
		{
			r: 25,
			c: 5,
			v: {
				v: "Center Left",
				ct: { fa: "General", t: "g" },
				m: "Center Left",
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: "1",
				vt: "0"
			}
		},
		{
			r: 25,
			c: 6,
			v: {
				v: "Center Center",
				ct: { fa: "General", t: "g" },
				m: "Center Center",
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: "0",
				vt: "0"
			}
		},
		{
			r: 25,
			c: 7,
			v: {
				v: "Center Right",
				ct: { fa: "General", t: "g" },
				m: "Center Right",
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: "2",
				vt: "0"
			}
		},
		{
			r: 25,
			c: 8,
			v: {
				v: "Bottom Left",
				ct: { fa: "General", t: "g" },
				m: "Bottom Left",
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: "1",
				vt: "2"
			}
		},
		{
			r: 25,
			c: 9,
			v: {
				v: "Bottom Center",
				ct: { fa: "General", t: "g" },
				m: "Bottom Center",
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: "0",
				vt: "2"
			}
		},
		{
			r: 25,
			c: 10,
			v: {
				v: "Bottom Right",
				ct: { fa: "General", t: "g" },
				m: "Bottom Right",
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: "2",
				vt: "2"
			}
		},
		{
			r: 26,
			c: 0,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 26,
			c: 1,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 26,
			c: 2,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 26,
			c: 3,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 26,
			c: 4,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 26,
			c: 5,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 26,
			c: 6,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 26,
			c: 7,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 26,
			c: 8,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 26,
			c: 9,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 26,
			c: 10,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 27,
			c: 0,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 27,
			c: 1,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 27,
			c: 2,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 27,
			c: 3,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 27,
			c: 4,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 27,
			c: 5,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 27,
			c: 6,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 27,
			c: 7,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 27,
			c: 8,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 27,
			c: 9,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 27,
			c: 10,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 28,
			c: 0,
			v: {
				v: "WordWrap",
				ct: { fa: "General", t: "g" },
				m: "WordWrap",
				bg: null,
				bl: 1,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 28,
			c: 1,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 28,
			c: 2,
			v: {
				v: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
				ct: { fa: "General", t: "g" },
				m: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1,
				tb: "2"
			}
		},
		{
			r: 28,
			c: 3,
			v: {
				ct: { fa: "General", t: "g" },
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1,
				tb: "1"
			}
		},
		{
			r: 28,
			c: 4,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 28,
			c: 5,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 28,
			c: 6,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 28,
			c: 7,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 28,
			c: 8,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 28,
			c: 9,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 28,
			c: 10,
			v: {
				bg: null,
				bl: 0,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		},
		{
			r: 29,
			c: 0,
			v: {
				ct: {
					fa: "General",
					t: "inlineStr",
					s: [
						{
							ff: '"times new roman"',
							fc: "rgb(51, 51, 51)",
							fs: "12",
							cl: 0,
							un: 0,
							bl: 1,
							it: 0,
							v: "TextRotate"
						}
					]
				},
				ht: "1",
				vt: "0"
			}
		},
		{
			r: 29,
			c: 2,
			v: {
				ct: { fa: "General", t: "g" },
				v: "I am Luckysheet text rotate style",
				m: "I am Luckysheet text rotate style",
				tr: "1",
				tb: "2",
				ht: "1",
				fs: "12"
			}
		},
		{
			r: 29,
			c: 3,
			v: {
				ct: { fa: "General", t: "g" },
				v: "I am Luckysheet text rotate style",
				m: "I am Luckysheet text rotate style",
				tr: "2",
				tb: "2",
				ht: "0",
				fs: "12"
			}
		},
		{
			r: 29,
			c: 4,
			v: {
				ct: { fa: "General", t: "g" },
				v: "I am Luckysheet text rotate style",
				m: "I am Luckysheet text rotate style",
				tr: "4",
				tb: "2",
				ht: "1",
				fs: "12",
				vt: "2"
			}
		},
		{
			r: 29,
			c: 5,
			v: {
				ct: { fa: "General", t: "g" },
				v: "I am Luckysheet text rotate style",
				m: "I am Luckysheet text rotate style",
				tr: "5",
				tb: "2",
				ht: "1",
				fs: "12"
			}
		},
		{
			r: 29,
			c: 6,
			v: {
				ct: { fa: "General", t: "g" },
				v: "I am Luckysheet text rotate style",
				m: "I am Luckysheet text rotate style",
				tr: "1",
				tb: "1",
				ht: "1",
				fs: "12",
				vt: "0"
			}
		},
		{
			r: 30,
			c: 0,
			v: { ct: { fa: "General", t: "g" }, v: "hidden1", m: "hidden1" }
		},
		{
			r: 31,
			c: 0,
			v: { m: "hidden2", ct: { fa: "General", t: "g" }, v: "hidden2" }
		},
		{
			r: 33,
			c: 0,
			v: {
				ct: { fa: "General", t: "g" },
				bg: null,
				bl: 1,
				it: 0,
				ff: 0,
				fs: 11,
				fc: "rgb(51, 51, 51)",
				ht: 1,
				vt: 1
			}
		}
	],
	ch_width: 2361,
	rh_height: 936,
	luckysheet_select_save: [
		{
			left: 741,
			width: 138,
			top: 796,
			height: 19,
			left_move: 741,
			width_move: 138,
			top_move: 796,
			height_move: 19,
			row: [33, 33],
			column: [6, 6],
			row_focus: 33,
			column_focus: 6
		}
	],
	calcChain: [
		{
			r: 0,
			c: 3,
			index: "0",
			func: [true, 3, "=Formula!A1+Formula!B1"],
			color: "w",
			parent: null,
			chidren: {},
			times: 0
		}
	],
	scrollLeft: 0,
	scrollTop: 0
};




async function injectDeps(deps) {
	return await new Promise((resolve, reject) => {
		if (!Array.isArray(deps)) {
			deps = [deps];
		}
		window.dojoDynamicRequire(deps, function () { resolve(Array.from(arguments)) });
	});
}

const cache = new Map();

// END EXTRA CODE

/**
 * @param {string} containerId
 * @param {string} config - start,offset:entity name;

2,1:LuckySheet.Entity;a:Name
 * @returns {Promise.<void>}
 */
export async function RenderSheet4EntityOverlap(containerId, config) {
	// BEGIN USER CODE
	let isVertical = true, entity, columns = new Map(), offset, start;
	config.split(';').forEach(d => {
		const e = d.split(':');
		switch (e[0]) {
			case 'entity':
				if (isNaN(+e[1])) {
					isVertical = false;
					start = parseInt(e[1], 36) - 9;
				} else {
					start = +e[1];
				}
				offset = +e[2];
				entity = e[3];//entity qualify name
				break;

			case 'column':
				if (!isNaN(+e[1])) {
					isVertical = false;
				}
				const loc = isVertical ? parseInt(e[1], 36) - 9 : +e[1];
				columns.set(loc, [loc, e[2]]);
				break;
		}
	})
	const container = document.querySelector('#' + containerId);
	function sendCommand(msg) {
		msg.mx_luckysheet.widgetid = containerId;
		container.querySelector('#lsWindow').contentWindow && container.querySelector('#lsWindow').contentWindow.postMessage(msg, '*');

	}
	const [html] = await injectDeps('dojo/html');
	let entityData = {
		"name": entity, //Worksheet name
		"color": "", //Worksheet color
		"index": 1, //Worksheet index
		"status": 0, //Worksheet active status
		"order": 1, //The order of the worksheet
		"hide": 0,//Whether worksheet hide 
		"row": 36, //the number of rows in a sheet
		"column": 18, //the number of columns in a sheet
		"defaultRowHeight": 19, //Customized default row height
		"defaultColWidth": 73, //Customized default column width
		"celldata": [], //Initial the cell data
		"config": {
			"merge": {}, //merged cells
			"rowlen": {}, //Table row height
			"columnlen": {}, //Table column width
			"rowhidden": {}, //hidden rows
			"colhidden": {}, //hidden columns
			"borderInfo": {}, //borders
			"authority": {}, //Worksheet protection
		},
		"scrollLeft": 0, //Left and right scroll bar position
		"scrollTop": 0, //Up and down scroll bar position
		"luckysheet_select_save": [], //selected area
		"calcChain": [],//Formula chain
		"isPivotTable": false,//Whether is pivot table
		"pivotTable": {},//Pivot table settings
		"filter_select": {},//Filter range
		"filter": null,//Filter configuration
		"luckysheet_alternateformat_save": [], //Alternate colors
		"luckysheet_alternateformat_save_modelCustom": [], //Customize alternate colors	
		"luckysheet_conditionformat_save": {},//condition format
		"frozen": {}, //freeze row and column configuration
		"chart": [], //Chart configuration
		"zoomRatio": 1, // zoom ratio
		"image": [], //image
		"showGridLines": 1, //Whether to show grid lines
	};

	async function updateEntity() {
		const [objs, extra] = await fetchPage(entity, Array.from(columns.values()).map(d => d[1]));

		cache.set(containerId, objs);
		const myData = [];
		objs.forEach((obj, i) => {
			for (const col of columns.values()) {
				myData.push({
					r: isVertical ? start + i * offset : col[0] - 1,
					c: isVertical ? col[0] - 1 : start + i * offset,
					v: {
						bg: null,
						bl: 0,
						it: 0,
						ff: 0,
						fs: 11,
						fc: "rgb(51, 51, 51)",
						ht: 1,
						vt: 1,
						v: obj.get(col[1]).toNumber ? obj.get(col[1]).toNumber() : obj.get(col[1]),
						ct: { fa: "General", t: "n" },
						//m: "3"
					}
				});
			}

		});

		entityData.celldata = myData;
		demo.status = 0;
		entityData.status = 1;

		sendCommand({
			mx_luckysheet: {
				id: 'setup', data: [
					demo,
					entityData
				],
				lang: mx.session.sessionData.locale.code.split('_')[0]
			}
		});
	}

	//响应LuckySheet事件
	window.addEventListener("message", (event) => {
		if (event.data.mx_luckysheet && event.data.mx_luckysheet.widgetid === containerId) {

			if (event.data.mx_luckysheet.id === 'load') {
				//事件 成功载入
				sendCommand({
					mx_luckysheet: {
						id: 'setup',
						data: [demo], lang: mx.session.sessionData.locale.code.split('_')[0]
					}
				});

				//加载数据
				updateEntity();
				//监听实体事件
				var subscription1 = mx.data.subscribe({
					entity: entity,
					callback: function (entity) {
						console.log("Update on entity " + entity);
						updateEntity();
					}
				});

			} else if (event.data.mx_luckysheet.id === 'cell_updated') {
				const data = event.data.mx_luckysheet.data;
				const idx = isVertical ? (data.r - start) / offset : (data.c - start) / offset;
				const obj = cache.get(containerId)[idx];
				if (isVertical) {
					obj.set(columns.get(data.c + 1)[1], data.newValue.v);
				} else {
					obj.set(columns.get(data.r + 1)[1], data.newValue.v);
				}
				mx.data.commit({
					mxobj: obj,
					callback: function () {
						console.log("Object committed");
						mx.data.update({
							entity: entity,
						});
					},
					error: function (e) {
						console.error("Could not commit object:", e);
					}
				});
			}

		}
	}, false);

	if (container.innerHTML == '') {

		//首次渲染
		html.set(container, `
<input type="file" name="upload" id="upload" />
		<iframe id="lsWindow" src="resources/luckysheet.html?widgetid=${containerId}" style="
    width: 100%;
    height: 100%;
    border: 0;
"></iframe>
		`);

		//响应模板变化
		const ul = container.querySelector('#upload');
		ul.onchange = function () {
			sendCommand({
				mx_luckysheet:
				{
					id: 'setup',
					data: ul.files[0], lang: mx.session.sessionData.locale.code.split('_')[0]
				}
			});
		}


	} else {

	}
	// END USER CODE
}
