// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} widgetid
 * @param {string} value
 * @returns {Promise.<void>}
 */
export async function SetSelectCellValue(widgetid, value) {
	// BEGIN USER CODE
	document.querySelector(`#${widgetid} iframe`).contentWindow
		&& document.querySelector(`#${widgetid} iframe`).contentWindow.postMessage({
			mx_luckysheet: {
				id: 'setValue',
				data: value,
				widgetid
			}
		}, '*');
	// END USER CODE
}
